namespace Sandbox.Components.Pages.Atlas.Maps
{
    /// <summary>
    /// Represents global lookups for Azure Maps.
    /// </summary>
    internal static class AtlasGlobalUI
    {
        /// <summary>
        /// Gets a dictionary of supported languages for Azure Maps, where the key is the language code and the value is the language name.
        /// </summary>
        public static Dictionary<string, string> Languages => new(languages);

        /// <summary>
        /// Gets a dictionary of supported views for Azure Maps, where the key is the view code and the value is the view name.
        /// </summary>
        public static Dictionary<string, string> Views => new(views);

        private static readonly Dictionary<string, string> languages = new() {
            { "af", "Afrikaans" },
            { "sq", "Albanian" },
            { "am", "Amharic" },
            { "ar-sa", "Arabic (Saudi Arabia)" },
            { "hy", "Armenian" },
            { "as", "Assamese" },
            { "az-Latn", "Azerbaijani (Latin)" },
            { "bn-BD", "Bangla (Bangladesh)" },
            { "bn-IN", "Bangla (India)" },
            { "eu", "Basque" },
            { "be", "Belarusian" },
            { "bn", "Bangla" },
            { "bs", "Bosnian (Latin)" },
            { "bg", "Bulgarian" },
            { "my", "Burmese" },
            { "ca", "Catalan Spanish" },
            { "ku-Arab", "Central Kurdish" },
            { "chr", "Cherokee" },
            { "zh-Hans", "Chinese (Simplified)" },
            { "zh-Hant", "Chinese (Traditional)" },
            { "zh-HanT-TW", "Chinese (Traditional, Taiwan)" },
            { "hr", "Croatian" },
            { "cs", "Czech" },
            { "da", "Danish" },
            { "prs-Arab", "Dari" },
            { "nl", "Dutch" },
            { "nl-BE", "Dutch (Belgium)" },
            { "nl-NL", "Dutch (Netherlands)" },
            { "en-NZ", "English (New Zealand)" },
            { "en-GB", "English (United Kingdom)" },
            { "en-US", "English (United States)" },
            { "et", "Estonian" },
            { "fo", "Faroese" },
            { "fil-Latn", "Filipino" },
            { "fi", "Finnish" },
            { "fr", "French" },
            { "fr-CA", "French (Canada)" },
            { "fr-FR", "French (France)" },
            { "fy", "Frisian" },
            { "gl", "Galician" },
            { "ka", "Georgian" },
            { "de-de", "German (Germany)" },
            { "el", "Greek" },
            { "kl", "Greenlandic" },
            { "gu", "Gujarati" },
            { "ha-Latn", "Hausa (Latin)" },
            { "haw", "Hawaiian" },
            { "he", "Hebrew" },
            { "hi", "Hindi" },
            { "hu", "Hungarian" },
            { "is", "Icelandic" },
            { "ig-Latn", "Igbo" },
            { "id", "Indonesian" },
            { "iu", "Inuktitut" },
            { "ga", "Irish" },
            { "xh", "isiXhosa" },
            { "zu", "isiZulu" },
            { "it", "Italian (Italy)" },
            { "ja", "Japanese" },
            { "kn", "Kannada" },
            { "kk", "Kazakh" },
            { "km", "Khmer" },
            { "qut-Latn", "K'iche'" },
            { "rw", "Kinyarwanda" },
            { "sw", "Kiswahili" },
            { "kok", "Konkani" },
            { "ko", "Korean" },
            { "ky-Cyrl", "Kyrgyz" },
            { "lo", "Lao" },
            { "lv", "Latvian" },
            { "lt", "Lithuanian" },
            { "lb", "Luxembourgish" },
            { "mk", "Macedonian" },
            { "ms", "Malay (Malaysia)" },
            { "ml", "Malayalam" },
            { "mt", "Maltese" },
            { "mi-Latn", "Maori" },
            { "mr", "Marathi" },
            { "mn-Cyrl", "Mongolian (Cyrillic)" },
            { "ne", "Nepali (Nepal)" },
            { "no", "Norwegian" },
            { "nb", "Norwegian (Bokmål)" },
            { "nn", "Norwegian (Nynorsk)" },
            { "or", "Odia" },
            { "ps", "Pashto" },
            { "fa", "Persian" },
            { "pl", "Polish" },
            { "pt", "Portuguese" },
            { "pt-BR", "Portuguese (Brazil)" },
            { "pt-PT", "Portuguese (Portugal)" },
            { "pa-Arab", "Punjabi (Arabic)" },
            { "pa", "Punjabi (Gurmukhi)" },
            { "quz", "Quechua (Peru)" },
            { "ro", "Romanian (Romania)" },
            { "rm", "Romansh" },
            { "ru", "Russian" },
            { "se", "Sami (Northern)" },
            { "sa", "Sanskrit" },
            { "gd-Latn", "Scottish Gaelic" },
            { "sr", "Serbian" },
            { "sr-Cyrl-BA", "Serbian (Cyrillic, Bosnia and Herzegovina)" },
            { "sr-Cyrl-ME", "Serbian (Cyrillic, Montenegro)" },
            { "sr-Cyrl-RS", "Serbian (Cyrillic, Serbia)" },
            { "sr-Latn", "Serbian (Latin)" },
            { "sr-Latn-ME", "Serbian (Latin, Montenegro)" },
            { "sr-Latn-RS", "Serbian (Latin, Serbia)" },
            { "nso", "Sesotho sa Leboa" },
            { "tn", "Setswana" },
            { "sd-Arab", "Sindhi (Arabic)" },
            { "si", "Sinhala" },
            { "sk", "Slovak" },
            { "sl", "Slovenian" },
            { "es", "Spanish" },
            { "es-MX", "Spanish (Mexico)" },
            { "es-ES", "Spanish (Spain)" },
            { "sv", "Swedish (Sweden)" },
            { "syr", "Syriac" },
            { "tg-Cyrl-TJ", "Tajik (Cyrillic)" },
            { "ta", "Tamil" },
            { "tt-Cyrl", "Tatar (Cyrillic)" },
            { "te", "Telugu" },
            { "th", "Thai" },
            { "bo", "Tibetan" },
            { "ti", "Tigrinya" },
            { "to", "Tongan" },
            { "tr", "Turkish" },
            { "tk-Latn", "Turkmen (Latin)" },
            { "uk", "Ukrainian" },
            { "ur", "Urdu" },
            { "ug-Arab", "Uyghur" },
            { "uz-Latn", "Uzbek (Latin)" },
            { "ca-ES-valencia", "Valencian" },
            { "vi", "Vietnamese" },
            { "cy", "Welsh" },
            { "wo", "Wolof" },
            { "yo-Latn", "Yoruba" },
        };

        private static readonly Dictionary<string, string> views = new() {
            { "auto", "Automatically detect" },
            { "Unified", "Unified View (Others)" },
            { "AE", "United Arab Emirates (Arabic View)" },
            { "AR", "Argentina (Argentinian View)" },
            { "BH", "Bahrain (Arabic View)" },
            { "IN", "India (Indian View)" },
            { "IQ", "Iraq (Arabic View)" },
            { "JO", "Jordan (Arabic View)" },
            { "KW", "Kuwait (Arabic View)" },
            { "LB", "Lebanon (Arabic View)" },
            { "MA", "Morocco (Moroccan View)" },
            { "OM", "Oman (Arabic View)" },
            { "PK", "Pakistan (Pakistani View)" },
            { "PS", "Palestinian Authority (Arabic View)" },
            { "QA", "Qatar (Arabic View)" },
            { "SA", "Saudi Arabia (Arabic View)" },
            { "SY", "Syria (Arabic View)" },
            { "US", "United States of America" },
            { "YE", "Yemen (Arabic View)" }
        };

        /// <summary>
        /// Gets the default language code for Azure Maps, which is "en-US" (English - United States).
        /// </summary>
        public static readonly string DefaultLanguage = "en-US";

        /// <summary>
        /// Gets the default view code for Azure Maps, which is "auto" (Automatically detect).
        /// </summary>
        public static readonly string DefaultView = "auto";
    }
}
